{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jaeger-bomb.serviceAccountName" . }}
  labels:
{{ include "jaeger-bomb.labels" . | nindent 4 }}
{{- end -}}
