apiVersion: v1
kind: Service
metadata:
  name: "jaeger-bomb-server"
  labels:
    app: "jaeger-bomb-server"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: "jaeger-bomb-server"
